language: c
sudo: false
compiler:
- clang
- gcc
script:
- ./autogen.sh
- ./configure
- make distcheck
deploy:
  provider: releases
  api_key:
    secure: fVMvvlhsginfIB7gEhAoKG7xzvF6D94yl8Z+jjfHQG4YtG3SScKVeQUnpWK7NhT90uoUfPnxd5dN3ZWlApoLBSz7iVD0sT1+VGYerM0Gn3LTUj3xvTB3WAAft6YePKhQeJfduzSNqsRjQ7buKgI1SFH0Ek5xwZe4Kl/O/D2Tsw0=
  file_glob: true
  file: nanomsg*.zip
  file: nanomsg*.tar.gz
  on:
    repo: nanomsg/nanomsg
    branch: travis
